/**
 * docs/evidence/README.md, generated: an index of every doc under docs/evidence/, titled and summarized
 * from the doc's own first heading and first paragraph — so a new evidence doc appears here automatically
 * and a removed one disappears, with nothing to hand-edit or forget.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';

export interface EvidenceDoc { file: string; title: string; summary: string }

export function listEvidenceDocs(dir = 'docs/evidence'): EvidenceDoc[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md') && f !== 'README.md')
    .sort()
    .map((file) => {
      const text = readFileSync(`${dir}/${file}`, 'utf8');
      const lines = text.split('\n');
      const title = /^#\s+(.+)/u.exec(lines[0] ?? '')?.[1] ?? file;
      const summary = lines.slice(1).find((l) => l.trim() && !l.startsWith('#'))?.trim().slice(0, 140) ?? '';
      return { file, title, summary };
    });
}

export function renderEvidenceIndex(docs: readonly EvidenceDoc[]): string {
  const rows = docs.map((d) => `| [\`${d.file}\`](./${d.file}) | ${d.title} | ${d.summary} |`);
  return `# Evidence\n\nGenerated by \`scripts/evidence-index.ts\` from the files in this folder — do not hand-edit; run \`npx tsx scripts/evidence-index.ts\` after adding or removing an evidence doc.\n\n| doc | title | what it shows |\n|---|---|---|\n${rows.join('\n')}\n`;
}

if (import.meta.url === `file://${process.argv[1]}`) writeFileSync('docs/evidence/README.md', renderEvidenceIndex(listEvidenceDocs()));
