/**
 * Requirement -> test trace. docs/contract.md tags every normative claim [C-###]; a test proves one by
 * carrying the same tag in its title or a nearby comment. `npm run check:trace` fails (exit 1) on any claim
 * with zero covering tests, printing one help-first line per gap. `--md <path>` also writes docs/evidence/trace.md.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

export interface Claim {
  id: string;
  text: string;
  line: number;
}
export interface TestTag {
  id: string;
  file: string;
}

const TAG = /\[C-(\d{3})\]/gu;

export function parseClaims(md: string): Claim[] {
  const lines = md.split('\n');
  const claims: Claim[] = [];
  lines.forEach((line, i) => {
    for (const m of line.matchAll(TAG)) claims.push({ id: `C-${m[1]}`, text: line.trim(), line: i + 1 });
  });
  return claims;
}

// Skips any "fixtures" directory: test/fixtures/trace/tests/*.test.ts are trace.ts's OWN tiny synthetic
// fixtures (test/unit/trace.test.ts calls findTags on that folder directly), not the real corpus. Without
// this, a real run over 'test' would also walk into them, and their [C-001]/[C-002] tags — reused on purpose,
// to pin the id format — would falsely "cover" docs/contract.md's real C-001/C-002 claims.
function walk(dir: string, out: string[] = []): string[] {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory() && e.name === 'fixtures') continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full, out);
    else if (e.name.endsWith('.test.ts')) out.push(full);
  }
  return out;
}

export function findTags(testRoot: string): TestTag[] {
  const out: TestTag[] = [];
  for (const file of walk(testRoot)) {
    const text = readFileSync(file, 'utf8');
    for (const m of text.matchAll(TAG)) out.push({ id: `C-${m[1]}`, file: file.split(path.sep).join('/') });
  }
  return out;
}

export interface TraceReport {
  claims: Claim[];
  covered: Set<string>;
  untraced: Claim[];
  unknownTags: TestTag[];
}

export function trace(claimsMd: string, testRoot: string): TraceReport {
  const claims = parseClaims(claimsMd);
  const claimIds = new Set(claims.map((c) => c.id));
  const tags = findTags(testRoot);
  const covered = new Set(tags.filter((t) => claimIds.has(t.id)).map((t) => t.id));
  return { claims, covered, untraced: claims.filter((c) => !covered.has(c.id)), unknownTags: tags.filter((t) => !claimIds.has(t.id)) };
}

export function renderTraceDoc(report: TraceReport): string {
  const rows = report.claims.map(
    (c) => `| ${c.id} | ${c.text.replace(/\[C-\d{3}\]/u, '').trim().slice(0, 80)} | ${report.covered.has(c.id) ? '✓' : '✖ untraced'} |`,
  );
  return `# Contract trace\n\ngenerated by \`scripts/trace.ts\` from \`docs/contract.md\` — do not hand-edit.\n\n${report.covered.size}/${report.claims.length} claims traced.\n\n| id | claim | test |\n|---|---|---|\n${rows.join('\n')}\n`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const report = trace(readFileSync('docs/contract.md', 'utf8'), 'test');
  const mdIdx = process.argv.indexOf('--md');
  if (mdIdx >= 0) writeFileSync(process.argv[mdIdx + 1]!, renderTraceDoc(report));
  for (const c of report.untraced) console.error(`✖ trace: ${c.id} is not covered by any test → tag the test that proves it with "[${c.id}]" in its title or a nearby comment`);
  if (report.untraced.length) {
    console.error(`✖ trace: ${report.untraced.length} untraced claim${report.untraced.length === 1 ? '' : 's'} → see above`);
    process.exit(1);
  }
  console.log(`${report.covered.size}/${report.claims.length} claims traced`);
}
