// Unlike tokens.md, this doc reports timings — never exactly reproducible run to run. "Not stale" means:
// the same script, at a small size, produces the same STRUCTURE (headings, per-op table shape, the do-not-
// hand-edit marker) and the committed numbers are internally sane, not that the numbers themselves match byte
// for byte.
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { renderBenchTable, runLedgerBench } from '../../scripts/bench-ledger.ts';

describe('docs/evidence/ledger-scale.md structure is current', () => {
  it('carries the generated-by marker and the same section/column shape a fresh small run produces', async () => {
    const committed = readFileSync('docs/evidence/ledger-scale.md', 'utf8');
    expect(committed).toContain('generated by `scripts/bench-ledger.ts`');

    const fresh = renderBenchTable(await runLedgerBench([300]));
    const headings = (s: string) => [...s.matchAll(/^#+ .+$/gmu)].map((m) => m[0].replace(/^#+\s*/u, ''));
    // Every `### op` section a fresh run produces must still have a same-named section in the committed doc —
    // the committed doc may have MORE (prose headings), never fewer of the script's own sections.
    for (const h of headings(fresh)) expect(headings(committed)).toContain(h);

    // Every "| n | samples | p50 ms | p95 ms |" table (one per timed op) must have p95 >= p50 on every row.
    const opTableBlock = /\|\s*n\s*\|\s*samples\s*\|\s*p50 ms\s*\|\s*p95 ms\s*\|\n\|[-|\s]+\|\n((?:\|.*\|\n?)*)/gu;
    let sawAnOpTable = false;
    for (const block of committed.matchAll(opTableBlock)) {
      sawAnOpTable = true;
      for (const row of block[1]!.trim().split('\n')) {
        const cols = row
          .split('|')
          .map((c) => c.trim())
          .filter(Boolean);
        const [, , p50, p95] = cols;
        expect(Number(p95)).toBeGreaterThanOrEqual(Number(p50));
      }
    }
    expect(sawAnOpTable).toBe(true);
  }, 60_000); // the fresh bench run timed out once at the 5 s default on Node 22
});
