// Unlike tokens.md, this doc reports timings — never exactly reproducible run to run. "Not stale" means:
// the same script, at a small size, produces the same STRUCTURE (headings, columns, the do-not-hand-edit
// marker) and the committed numbers are internally sane, not that the numbers themselves match byte for byte.
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { renderBenchTable, runLedgerBench } from '../../scripts/bench-ledger.ts';

describe('docs/evidence/ledger-scale.md structure is current', () => {
  it('carries the generated-by marker and the same section/column shape a fresh small run produces', async () => {
    const committed = readFileSync('docs/evidence/ledger-scale.md', 'utf8');
    expect(committed).toContain('generated by `scripts/bench-ledger.ts`');
    const fresh = renderBenchTable(await runLedgerBench([300]));
    const headings = (s: string) => [...s.matchAll(/^#+ .+$/gmu)].map((m) => m[0]);
    expect(headings(committed).length).toBeGreaterThanOrEqual(headings(fresh).length);
    for (const row of committed.matchAll(/\|\s*\d[\d,]*\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|/gu)) {
      expect(Number(row[2])).toBeGreaterThanOrEqual(Number(row[1])); // p95 >= p50, every timing row
    }
  });
});
